name: build CAS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: build the exploded CAS webapp
        run: |
          ./gradlew explodeWarOnly

      - name: Build a docker image
        run: |
          docker build -t georchestra/cas:6.3-dev .
      
      - name: Build a war file
        run: |
          ./gradlew build
          
      - name: publish the artifact
        if: github.repository == 'georchestra/georchestra-cas-server' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: cas.war
          path: build/libs/cas.war
      
      - uses: docker/login-action@v1
        if: github.repository == 'georchestra/georchestra-cas-server' && github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Publish the docker image
        if: github.repository == 'georchestra/georchestra-cas-server' && github.ref == 'refs/heads/master'
        run: |
          docker push georchestra/cas:6.3-dev
